nasm = nasm-2.16rc12/nasm.exe
disk = F:/
qemu = qemu/qemu.exe
file = ../stsKenrel.img
stsKenrel.img: bin/boot.bin bin/test.bin
	dd if=bin/boot.bin of=stsKenrel.img bs=512 count=1
	dd if=bin/test.bin of=stsKenrel.img bs=512 seek=1 conv=notrunc
bin/boot.bin: stsBoot/boot.asm
	$(nasm) stsBoot/boot.asm -o bin/boot.bin
bin/test.bin: test.asm
	$(nasm) test.asm -o bin/test.bin
del:
	cmd /c del stsKenrel.img